services:
  prometheus-kafka-adapter:
    image: telefonica/prometheus-kafka-adapter:1.9.0
    environment:
      KAFKA_BROKER_LIST: kafka-broker-ip:9092
      KAFKA_TOPIC: kafka-topic-name
      SERIALIZATION_FORMAT: json
      PORT: 8080
      LOG_LEVEL: debug
      GIN_MODE: release
      KAFKA_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_SASL_MECHANISM: PLAIN
      KAFKA_SASL_USERNAME: "***"
      KAFKA_SASL_PASSWORD: "***"
    ports:
      - "8080:8080"
