# Try to include optional files. Any settings in these files override the main settings.
IncludeOptional:
    # Secure Kafka settings
    - datagen_secret.yml
General:
    minSleep: 0.02
    maxSleep: 0.08
    maxUsers: 100000
    eventTopic: "dg-events-2"
Kafka:
    bootstrap.servers: "localhost:9092"
State:
    db: "datagen_state.db"
